### ISSUE TITLE
能不能增加一个自定义配置的文件

### ISSUE THREAD

**Issue by longgangfan** [muzuiget/redisposition#1]
这个插件很实用，但是出现下载乱码的网站毕竟是少数的，能不能设置一个配置文件，用户可以定义对特定的网站使用指定的编码。这样的好处是不用每次都去切换，一次设置好，后面就不用再管了。

**Comment by muzuiget** [comment]
这玩意居然还有人在用……简单说，不想加，我已经对者扩展失去兴趣，加上这功能要改很多界面代码。

但是你总可以自己改代码硬编码进去，整个扩展真正干活的核心代码就那么几行

https://github.com/muzuiget/redisposition/blob/master/bootstrap.js#L579-L603

其余都是怎么读取配置，所以你只需要读取 `channel.originalURI`，得到网址，然后决定用那个编码，重新打包 xpi 安装完事。
